### PR TITLE
Added the oficial logo

### PR DESCRIPTION
**Pull request by RaphaelSanches**
Hi! I have made some changes for add the logo in the site. Tomorrow I will change the colors scheme.

I have followed the contributing guidelines, but is my first contribution for a open source project and can have some mistakes on this step.

### CODE REVIEW

**Comment by ghost** [comment]
Your pull request doesn't follow our guidelines. Please fix the following:
- Pull request title must be in past tense (e.g. "added", "fixed", "changed") [(?)](https://gitmagic.io/rules/#/pull-request/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/seu-as-code/seu-as-code.github.io/16/af53565c-9471-4f73-accd-8e99faa187ed/e31ca9cc-ef2e-440c-bd29-0aac151734f3) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, the title and description now looks good! :bowtie:

**Comment by lreimer** [comment]
@RaphaelSanches looks good so far. However, in Safari on MacOS the logo is way to big, it does not scale properly. This does not happen in Firefox for example. Can you somehow adjust the SVG and make it slightly smaller(maybe 500 width)

**Comment by RaphaelSanches** [comment]
@lreimer Sorry for the delay. Test again, please (i don't have a Mac OS here D: ).

**Pull request merged**
